# Lesli
# 
# Copyright (c) 2025, Lesli Technologies, S. A.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program. If not, see http://www.gnu.org/licenses/.
# 
# Lesli · Ruby on Rails SaaS Development Framework.
# 
# Made with ♥ by LesliTech
# Building a better future, one line of code at a time.
# 
# @contact  hello@lesli.tech
# @website  https://www.lesli.tech
# @license  GPLv3 http://www.gnu.org/licenses/gpl-3.0.en.html
# 
# // · ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~
# // · 



# -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-
# REUSABLE GITHUB ACTIONS WORKFLOWS DESIGNED TO BE USED ACROSS 
# THE LESLI FRAMEWORK REPOSITORIES
# -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-



# Specs for The Lesli Framework
# -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-
name: "Lesli SQLite Test Workflow"
on:
  workflow_dispatch:    # This allows the action to be executed on demand
  workflow_call:        # This allows the workflow to be reusable
    inputs:
      branch:
        required: true
        type: string

jobs:
  sqlite-test:
    name: SQLite test workflow
    runs-on: ubuntu-latest

    # Do not execute the test if requests comes from another action
    if: ${{ !contains(github.event.head_commit.message, 'ci(workflows):') && !contains(github.event.head_commit.message, 'release(gem):') && !contains(github.event.head_commit.message, 'assets(js):') }}

    steps:

      # Clone LesliBuilder repository
      - name: Checkout LesliBuilder repository
        uses: actions/checkout@v4
        with:
          repository: LesliTech/LesliBuilder

      # Clone LesliActions repository
      - name: Checkout LesliActions repository
        uses: actions/checkout@v4
        with:
          path: ./enginesdev/LesliActions
          repository: LesliTech/LesliActions

      # Clone Lesli core repository
      - name: Checkout Lesli repository
        uses: actions/checkout@v4
        if: github.event.repository.name != 'Lesli'
        with:
          path: ./engines/Lesli
          repository: LesliTech/Lesli

      # Clone engine repository
      - name: Checkout engine repository
        uses: actions/checkout@v4
        if: github.event.repository.name != 'LesliActions'
        with:
          path: ./engines/${{ github.event.repository.name }}
          repository: LesliTech/${{ github.event.repository.name }}

      # Prepare configuration files
      - name: Copy configuration files
        run: |
          rm ./Gemfile.lock
          rm ./Gemfile.lesli
          cp ./enginesdev/LesliActions/config/rails/Gemfile.lesli ./Gemfile.lesli
          cp ./enginesdev/LesliActions/config/rails/database_sqlite.yml ./config/database.yml

      # Use the official receipt to install ruby in ubuntu
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.5
          bundler-cache: true

      # Build the Lesli database
      - name: Set up SQLite database
        run: RAILS_ENV=test bundle exec rake lesli:db:reset
        env:
          RAILS_ENV: test

      # Run Rspec tests & collect coverage
      - name: Run Rails tests with SQLite
        run: bundle exec rails test
        env:
          COVERAGE: true

      - name: Upload test results to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage/coverage.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload Test Results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v5
        with:
          report_type: test_results
          files: ./test/reports/*.xml 
          token: ${{ secrets.CODECOV_TOKEN }}
